version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: job-api-app
    container_name: job-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - app-network
    ports:
      - "9000:9000"

  db:
    image: mysql:5.7
    container_name: job-api-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_api
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
